create table especialidad (id bigint not null auto_increment, nombre_especialidad varchar(255) not null, primary key (id))
create table especialidad_medicos (especialidad_id bigint not null, medicos_id bigint not null)
create table medico (id bigint not null auto_increment, apellido varchar(100) not null, codigo varchar(100) not null, nombre varchar(100) not null, numero_documento varchar(255) not null, tipo_documento varchar(255), primary key (id))
create table medico_especialidades (medico_id bigint not null, especialidades_id bigint not null)
create table paciente (id bigint not null auto_increment, apellido varchar(100) not null, codigo varchar(100) not null, nombre varchar(100) not null, numero_documento varchar(255) not null, tipo_documento varchar(255), primary key (id))
create table situacion_del_paciente (id bigint not null auto_increment, especialidad_id bigint, medico_id bigint, paciente_id bigint, primary key (id))
create table usuarios_sistema (id bigint not null auto_increment, apellido varchar(100) not null, email varchar(100) not null, failed_login integer not null, fecha_creacion datetime not null, is_active bit not null, is_locked bit not null, last_login datetime, nombre varchar(100) not null, password varchar(100) not null, username varchar(100) not null, primary key (id))
alter table usuarios_sistema add constraint UK_sdcwkw7s3xe2xx02s6d4x9qbn unique (email)
alter table usuarios_sistema add constraint UK_691e86xo91lah4ey74tqer7jn unique (username)
alter table especialidad_medicos add constraint FKbkhlftgloccpw97ws7q1v7svg foreign key (medicos_id) references medico (id)
alter table especialidad_medicos add constraint FK6p1wjqikjxjglte55lrevak3u foreign key (especialidad_id) references especialidad (id)
alter table medico_especialidades add constraint FKb09mp1tj75exb956rrfnrgwfb foreign key (especialidades_id) references especialidad (id)
alter table medico_especialidades add constraint FK8imkjtu6vid67l37gighb1ye5 foreign key (medico_id) references medico (id)
alter table situacion_del_paciente add constraint FKsibltyr69qg7cuwlhngw6vqj2 foreign key (especialidad_id) references especialidad (id)
alter table situacion_del_paciente add constraint FK7qq8enkfcx868xofe32mp92e6 foreign key (medico_id) references medico (id)
alter table situacion_del_paciente add constraint FKcdpigc0dkcm4anqcmi594o2lr foreign key (paciente_id) references paciente (id)
